"""add users table

Revision ID: 007519f013f1
Revises: 
Create Date: 2023-03-31 10:32:47.605439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007519f013f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
